// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjpnXNAlm7UmCJim74ip-UIDhBAFzM_w',
    appId: '1:931093926341:web:a0fbac5b417fbfe1e3fbac',
    messagingSenderId: '931093926341',
    projectId: 'zanzibar-tourism-dit',
    authDomain: 'zanzibar-tourism-dit.firebaseapp.com',
    storageBucket: 'zanzibar-tourism-dit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd-nQBZFetVr1PQf1rvk8ObEq2xgCbf6E',
    appId: '1:931093926341:android:491da83e4aa46672e3fbac',
    messagingSenderId: '931093926341',
    projectId: 'zanzibar-tourism-dit',
    storageBucket: 'zanzibar-tourism-dit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06yh3a8D60gAKLb6XbFlYwFD2tDFjRwk',
    appId: '1:931093926341:ios:391c1bf2fc64c5f9e3fbac',
    messagingSenderId: '931093926341',
    projectId: 'zanzibar-tourism-dit',
    storageBucket: 'zanzibar-tourism-dit.firebasestorage.app',
    iosBundleId: 'com.example.zanzibarTourism',
  );
}
